---

- name: Clean infra
  hosts: localhost
  connection: local
  gather_facts: no

  roles:

  - role: cloud-infra
    vars:
      state: absent
      terraform_project_version: 'fix/terraform_path'
