---

- name: Terraform Destroy
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    terraform_dir: "{{ playbook_dir }}/../../../../terraform"

  pre_tasks:
  - name: Get Terraform scripts
    git:
      repo: 'https://github.com/klusters/terraform-gcp-infra'
      dest: '{{ terraform_dir }}'
      version: 'main'

  - name: Generate Terraform vars
    template:
      src: "{{ playbook_dir }}/../../../templates/tfvars.json.j2"
      dest: '{{ terraform_dir }}/terraform.tfvars.json'
      mode: 0644

  tasks:
  - name: Terraform Destroy
    terraform:
      # binary_path: "{{ lookup('env','TERRAFORM_CLI_PATH') + '/terraform-bin' }}"
      force_init: yes
      project_path: '{{ terraform_dir }}'
      # workspace: "{{ lookup('env','MOLECULE_SCENARIO_NAME') }}"
      state: absent
