---

dependency:
  name: galaxy
  options:
    role-file: ../../inventories/gcp/molecule_test/requirements/ansible_requirements.yml

driver:
  name: delegated

lint: |
  yamllint .
  ansible-lint .

platforms:
- name: 'mandatory_section'
  groups: ['ignore_me']

provisioner:
  name: ansible
  playbooks:
    create: ../../playbooks/elasticsearch/pre/init_infra.yml
    prepare: ../../playbooks/elasticsearch/pre/config_infra.yml
    converge: ../../playbooks/elasticsearch/elasticsearch/install.yml
    verify: ../../playbooks/elasticsearch/elasticsearch/check.yml
    destroy: ../../playbooks/elasticsearch/post/clean_infra.yml
  ansible_args:
    - --inventory=../../inventories/gcp/molecule_test/gce_instances.gcp.yml
  inventory:
    links:
      hosts: ../../inventories/gcp/molecule_test/
      group_vars: ../../inventories/gcp/molecule_test/group_vars/
