---

- name: Config infra
  hosts: es_cluster
  gather_facts: no
  strategy: free

  pre_tasks:

  - name: Update package cache
    become: yes
    package: update_cache=yes
    changed_when: no
    register: task_result
    until: task_result is success
    retries: 10
    delay: 2

  roles:

  - role: klusters.system.etc_hosts
    vars:
      role_etc_hosts_group: es_cluster

  - role: klusters.system.entropy
  - role: klusters.system.filesystems
  - role: klusters.system.tcp_offload
