---

- name: Init infra
  hosts: localhost
  connection: local
  gather_facts: no

  roles:
  - role: cloud-infra
    vars:
      state: present
      terraform_project_version: 'fix/terraform_path'

- name: Check SSH availability
  hosts: all
  gather_facts: no

  tasks:
  - name: Wait for system to become reachable
    wait_for_connection:
      timeout: 90
      delay: 15
