---

- name: Init infra
  hosts: localhost
  connection: local
  gather_facts: no

  roles:

  - role: cloud-infra
    vars:
      state: present

- name: Check SSH availability
  hosts: es_cluster
  gather_facts: no

  tasks:

  - name: Wait for system to become reachable
    wait_for_connection:
      timeout: 90
      delay: 15
