---

es_api_scheme: "https"
es_api_host: "basic-cluster-es-http"
es_cluster_name: 'basic-cluster'
es_namespace: 'default'

es_api_basic_auth_username: 'elastic'
es_api_basic_auth_password: "{{ lookup('k8s', kind='Secret', namespace=es_namespace, resource_name=es_cluster_name + '-es-' + es_api_basic_auth_username + '-user')['data']['elastic'] | b64decode }}"

es_roles:
  native:
    sample_role_2:
      cluster: ['monitor']
      indices:
      - names: 'dummy-index-*'
        privileges:
        - read
        query:
          term:
            k8s_label1: app_name

...