---

es_api_scheme: "https"
es_api_host: "basic-cluster-es-http"
es_cluster_name: 'basic-cluster'
es_k8s_namespace: 'default'

es_api_basic_auth_username: 'elastic'
es_api_basic_auth_password: "{{ lookup('k8s', kind='Secret', namespace=es_k8s_namespace, resource_name=es_cluster_name + '-es-' + es_api_basic_auth_username + '-user')['data']['elastic'] | b64decode }}"

found_k8s_secrets: "{{ lookup('k8s', kind='Secret', namespace=es_k8s_namespace, label_selector='purpose=es_users,es_cluster=' + es_cluster_name) | json_query('[*].metadata.name')}}"

es_secrets_mode_enabled: yes
es_secrets_mode: k8s

es_roles:
  native:
    sample_role_2:
      cluster: ['monitor']
      indices:
      - names: 'dummy-index-*'
        privileges:
        - read
        # query:
        #   term:
        #     k8s_label1: app_name

es_users:
  native:
    dummy_user_1:
      password: '{% if es_cluster_name + "-es-dummy-user-1-user" in found_k8s_secrets %}{{ lookup("k8s", kind="Secret", namespace=es_k8s_namespace, resource_name=es_cluster_name + "-es-dummy-user-1-user")["data"]["user_password"] | b64decode }}{% else %}{{ lookup("password", "/dev/null chars=ascii_letters,digits" ) }}{% endif %}'
      roles:
      - sample_role_1
    dummy_user_2:
      password: '{% if es_cluster_name + "-es-dummy-user-2-user" in found_k8s_secrets %}{{ lookup("k8s", kind="Secret", namespace=es_k8s_namespace, resource_name=es_cluster_name + "-es-dummy-user-2-user")["data"]["user_password"] | b64decode }}{% else %}{{ lookup("password", "/dev/null chars=ascii_letters,digits" ) }}{% endif %}'
      roles:
      - sample_role_2
    dummy_user_3:
      password: '{% if es_cluster_name + "-es-dummy-user-3-user" in found_k8s_secrets %}{{ lookup("k8s", kind="Secret", namespace=es_k8s_namespace, resource_name=es_cluster_name + "-es-dummy-user-3-user")["data"]["user_password"] | b64decode }}{% else %}{{ lookup("password", "/dev/null chars=ascii_letters,digits" ) }}{% endif %}'
      roles:
      - sample_role_2
    metricbeat_collect_es:
      password: '{% if es_cluster_name + "-es-metricbeat-collect-es-user" in found_k8s_secrets %}{{ lookup("k8s", kind="Secret", namespace=es_k8s_namespace, resource_name=es_cluster_name + "-es-metricbeat-collect-es-user")["data"]["user_password"] | b64decode }}{% else %}{{ lookup("password", "/dev/null chars=ascii_letters,digits" ) }}{% endif %}'
      roles:
      - remote_monitoring_collector
      - enrich_user

...