---

es_api_scheme: "https"
es_api_host: "basic-cluster-es-http"
es_cluster_name: 'basic-cluster' # cannot contain '_'
es_k8s_namespace: 'default'

es_api_basic_auth_username: 'elastic'
es_api_basic_auth_password: "{{ lookup('k8s', kind='Secret', namespace=es_k8s_namespace, resource_name=es_cluster_name + '-es-' + es_api_basic_auth_username + '-user')['data']['elastic'] | b64decode }}"

found_k8s_secrets: "{{ lookup('k8s', kind='Secret', namespace=es_k8s_namespace, label_selector='purpose=es_users,es_cluster=' + es_cluster_name) | json_query('[*].metadata.name')}}"

es_secrets_mode_enabled: yes
es_secrets_mode: k8s

...