---

es_roles:
  native:
    sample_role_2:
      cluster: ['monitor']
      indices:
      - names: 'dummy-index-*'
        privileges:
        - read
        # query:
        #   term:
        #     k8s_label1: app_name
    filebeat_role:
      cluster:
        - cluster:admin/ilm/put
        - manage_index_templates
        - monitor
        - read_ilm
        - cluster:admin/ingest/pipeline/get
        - cluster:admin/ingest/pipeline/put
      indices:
        - names: 'filebeat-*'
          privileges:
            - create_index
            - create_doc
            - view_index_metadata
            - manage

...