---

es_data_config:
  node.data: true
  node.master: false
  node.voting_only: false
  node.ingest: false 
  node.ml: false

es_config: '{{ es_common_config | combine(es_data_config) }}'

es_heap_size: 1g

es_data_dirs:
  - "/data/01"
  - "/data/02"