---

name: "deploy"

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PY_COLORS: 1
      ANSIBLE_FORCE_COLOR: 1

    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          path: ansible-elasticsearch-klusters
      
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.13

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Python dependencies
        working-directory: ansible-elasticsearch-klusters
        run: |
          python -m pip install --upgrade pip
          pip install -r python_requirements.txt

      - name: Setup gcloud environment
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCLOUD_PROJECT }}
          service_account_key: ${{ secrets.GCLOUD_KEYFILE_JSON }}
          export_default_credentials: true

      - name: Run playbooks
        working-directory: ansible-elasticsearch-klusters
        run: |
          terraform --version
          ansible --version
          molecule test -s kickstart
